server.port=8085
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/microservice-project
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/ms-partner
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.open-in-view=false
# 'update' crée les tables automatiquement si elles n'existent pas
spring.jpa.hibernate.ddl-auto=update
# Spécifie le dialecte SQL pour PostgreSQL (optionnel mais recommandé)
# Affiche les requêtes SQL dans la console (très utile pour le développement)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:8761/eureka/}
##swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method
