
server.port=8087

# PostgreSQL DataSource
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/product_category_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/microservice-project}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWKS_URI:http://localhost:8180/realms/microservice-project/protocol/openid-connect/certs}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.open-in-view=false
# --- CONFIGURATION JPA / HIBERNATE ---
# 'update' cr�e les tables automatiquement si elles n'existent pas
spring.jpa.hibernate.ddl-auto=update
# Sp�cifie le dialecte SQL pour PostgreSQL (optionnel mais recommand�)
# Affiche les requ�tes SQL dans la console (tr�s utile pour le d�veloppement)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:8761/eureka/}


##swagger
#springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method



